services:
  - type: web
    name: evexticket-api
    runtime: python
    region: frankfurt
    plan: free
    buildCommand: "bash build.sh"
    startCommand: "bash start.sh"
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: DATABASE_ENGINE
        value: "django_cockroachdb"
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: CORS_ALLOW_ALL
        value: "True"
      - key: PYTHON_VERSION
        value: "3.12.3"




