"""
Django settings for togotrans_api project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
import dj_database_url
from decouple import Csv, config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY', default='django-insecure-k+qv%zb*h@6^htx=s291hq*ra8!2)9pym7mvpbda@jnt&-l$5@')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=True, cast=bool)

ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='*', cast=Csv())

for host in [
    '.evex-tg.local',
    '.evex-tg.com',
    'admin.evex-tg.local',
    'compagnie.evex-tg.local',
    'company.evex-tg.local',
    'admin.evex-tg.com',
    'compagnie.evex-tg.com',
    'company.evex-tg.com',
]:
    if host not in ALLOWED_HOSTS:
        ALLOWED_HOSTS.append(host)

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATIC_URL = '/static/'

# WhiteNoise pour servir les fichiers statiques en production
STORAGES = {
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

# Render deploy detection
RENDER_EXTERNAL_HOSTNAME = config('RENDER_EXTERNAL_HOSTNAME', default='')
if RENDER_EXTERNAL_HOSTNAME:
    ALLOWED_HOSTS.append(RENDER_EXTERNAL_HOSTNAME)


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',
    'corsheaders',
    'transport',
    'payments',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'togotrans_api.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'togotrans_api.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': dj_database_url.config(
        default=config('DATABASE_URL', default=f"sqlite:///{BASE_DIR / 'db.sqlite3'}"),
        conn_max_age=600,
        conn_health_checks=True,
    )
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/


# Configuration de la journalisation
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'loggers': {
        '': {  # Logger par défaut
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': True,
        },
    },
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Django REST Framework
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.TokenAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
}

# CORS settings
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
    "http://localhost:4173",
    "http://127.0.0.1:5173",
    "http://127.0.0.1:4173",
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://localhost:19006",
    "http://127.0.0.1:19006",
    "http://localhost:8081",
    "http://127.0.0.1:8081",
    "http://localhost:8084",
    "http://127.0.0.1:8084",
    "http://admin.evex-tg.local:5173",
    "http://compagnie.evex-tg.local:5173",
    "http://company.evex-tg.local:5173",
    "https://admin.evex-tg.local",
    "https://compagnie.evex-tg.local",
    "https://company.evex-tg.local",
    "http://admin.evex-tg.com:5173",
    "http://compagnie.evex-tg.com:5173",
    "http://company.evex-tg.com:5173",
    "https://admin.evex-tg.com",
    "https://compagnie.evex-tg.com",
    "https://company.evex-tg.com",
    "exp://localhost:19000",
]

CORS_ALLOWED_ORIGIN_REGEXES = [
    r"^https?://([a-z0-9-]+\.)?evex-tg\.local(:\d+)?$",
    r"^https?://([a-z0-9-]+\.)?evex-tg\.com(:\d+)?$",
]

# Add dynamic origins from environment if needed
_extra_cors = config('CORS_EXTRA_ORIGINS', default='')
if _extra_cors:
    CORS_ALLOWED_ORIGINS += [o.strip() for o in _extra_cors.split(',') if o.strip()]

# Allow all for local development (restrict in production)
CORS_ALLOW_ALL_ORIGINS = config('CORS_ALLOW_ALL', default=False, cast=bool)
CORS_ALLOW_CREDENTIALS = True
CSRF_TRUSTED_ORIGINS = [
    "http://localhost:5173",
    "http://127.0.0.1:5173",
    "http://admin.evex-tg.local:5173",
    "http://compagnie.evex-tg.local:5173",
    "http://company.evex-tg.local:5173",
    "https://admin.evex-tg.local",
    "https://compagnie.evex-tg.local",
    "https://company.evex-tg.local",
    "https://admin.evex-tg.com",
    "https://compagnie.evex-tg.com",
    "https://company.evex-tg.com",
]
# Configuration de la langue et du fuseau horaire
LANGUAGE_CODE = 'fr-fr'
TIME_ZONE = 'Africa/Lome'
USE_I18N = True
USE_TZ = True

# QOS / Qosic
QOS_API_KEY = config('QOS_API_KEY', default='')
QOS_SECRET_KEY = config('QOS_SECRET_KEY', default='')
QOS_BASE_URL = config('QOS_BASE_URL', default='https://api.qosic.net')
QOS_CALLBACK_URL = config('QOS_CALLBACK_URL', default='')

# QosPay (QosicBridge) - integration des operateurs mobile money
QOSPAY_BASE_URL = config('QOSPAY_BASE_URL', default='https://api.qosic.net')
QOSPAY_API_USERNAME = config('QOSPAY_API_USERNAME', default='')
QOSPAY_API_PASSWORD_TOGOCEL = config('QOSPAY_API_PASSWORD_TOGOCEL', default='')
QOSPAY_API_PASSWORD_MOOV = config('QOSPAY_API_PASSWORD_MOOV', default='')
QOSPAY_CLIENT_ID_TOGOCEL = config('QOSPAY_CLIENT_ID_TOGOCEL', default='')
QOSPAY_CLIENT_ID_MOOV = config('QOSPAY_CLIENT_ID_MOOV', default='')
QOSPAY_REQUEST_URL_TOGOCEL = config('QOSPAY_REQUEST_URL_TOGOCEL', default='')
QOSPAY_REQUEST_URL_MOOV = config('QOSPAY_REQUEST_URL_MOOV', default='')
QOSPAY_STATUS_URL_TOGOCEL = config('QOSPAY_STATUS_URL_TOGOCEL', default='')
QOSPAY_STATUS_URL_MOOV = config('QOSPAY_STATUS_URL_MOOV', default='')
QOSPAY_CALLBACK_URL = config('QOSPAY_CALLBACK_URL', default='')
QOSPAY_TIMEOUT = config('QOSPAY_TIMEOUT', default=30, cast=int)
QOSPAY_VERIFY_SSL = config('QOSPAY_VERIFY_SSL', default=True, cast=bool)

# Compatibilite avec les anciens noms encore presents dans certains modules.
QOSPAY_USERNAME = QOSPAY_API_USERNAME
QOSPAY_PASSWORD = config(
    'QOSPAY_API_PASSWORD',
    default=QOSPAY_API_PASSWORD_MOOV or QOSPAY_API_PASSWORD_TOGOCEL,
)
QOSPAY_CLIENT_ID = config(
    'QOSPAY_CLIENT_ID',
    default=QOSPAY_CLIENT_ID_MOOV or QOSPAY_CLIENT_ID_TOGOCEL,
)

# Reservation temporaire des sieges
SIEGE_EXPIRY_MINUTES = config('SIEGE_EXPIRY_MINUTES', default=5, cast=int)

