import React, { useCallback, useEffect, useState } from 'react';
import { ArrowLeft, Building2, Download, Loader2, Plus, Power, Search, ShieldCheck, Store, Users } from 'lucide-react';
import { Link, useParams } from 'react-router-dom';
import apiService from '../../services/api';
import type { PlatformAdminCompany } from '../../services/api';
import { AdminError, AdminLoading, AdminMetricCard, AdminModal, AdminPageShell, EmptyState, Field, PrimaryButton, SecondaryButton, StatusBadge, inputClass, money, number, selectClass, shortDate } from './AdminUI';

const emptyCompany = { name: '', description: '', address: '', phone: '', email: '', website: '', commission_rate: '10', admin_first_name: '', admin_last_name: '', admin_email: '', admin_password: '' };

export const AdminCompaniesPage: React.FC = () => {
  const [companies, setCompanies] = useState<PlatformAdminCompany[]>([]);
  const [filters, setFilters] = useState({ q: '', status: 'all' });
  const [form, setForm] = useState(emptyCompany);
  const [modal, setModal] = useState(false);
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const load = useCallback(async () => { setLoading(true); try { setCompanies(await apiService.getPlatformAdminCompanies(filters)); setError(null); } catch (err: any) { setError(err?.message || 'Impossible de charger les compagnies.'); } finally { setLoading(false); } }, [filters]);
  useEffect(() => { const id = window.setTimeout(() => void load(), 250); return () => window.clearTimeout(id); }, [load]);

  const create = async (event: React.FormEvent) => { event.preventDefault(); setSaving(true); setError(null); try { await apiService.createPlatformAdminCompany({ ...form, commission_rate: Number(form.commission_rate) }); setModal(false); setForm(emptyCompany); await load(); } catch (err: any) { setError(err?.message || 'Création impossible.'); } finally { setSaving(false); } };
  const toggle = async (company: PlatformAdminCompany) => { const next = !company.is_active; const reason = next ? 'Réactivation depuis le portail administrateur' : window.prompt(`Pourquoi suspendre ${company.name} ?`, '')?.trim(); if (!next && !reason) return; try { await apiService.setPlatformAdminCompanyStatus(company.id, next, reason || ''); await load(); } catch (err: any) { setError(err?.message || 'Mise à jour impossible.'); } };

  return <AdminPageShell title="Compagnies" description="Créez les partenaires, leurs comptes administrateurs, contrôlez leur statut et accédez à leur activité détaillée." actions={<div className="flex flex-wrap gap-2"><SecondaryButton onClick={() => void apiService.downloadPlatformAdminExport('companies')}><Download className="h-4 w-4" /> Exporter</SecondaryButton><PrimaryButton onClick={() => setModal(true)}><Plus className="h-4 w-4" /> Nouvelle compagnie</PrimaryButton></div>}>
    <AdminError message={error} onRetry={() => void load()} />
    <section className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><div className="grid gap-3 md:grid-cols-[1fr_220px]"><div className="relative"><Search className="pointer-events-none absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-400" /><input value={filters.q} onChange={(event) => setFilters((current) => ({ ...current, q: event.target.value }))} placeholder="Nom, email ou téléphone" className={`${inputClass} pl-10`} /></div><select value={filters.status} onChange={(event) => setFilters((current) => ({ ...current, status: event.target.value }))} className={selectClass}><option value="all">Tous les statuts</option><option value="active">Actives</option><option value="inactive">Suspendues</option></select></div></section>
    {loading ? <AdminLoading /> : companies.length === 0 ? <EmptyState title="Aucune compagnie trouvée" description="Modifiez les filtres ou créez le premier partenaire." /> : <section className="grid gap-5 xl:grid-cols-2">{companies.map((company) => <article key={company.id} className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex items-start justify-between gap-4"><div className="flex min-w-0 items-center gap-3"><div className="flex h-12 w-12 shrink-0 items-center justify-center rounded-2xl bg-blue-50 font-bold text-blue-700">{company.name.charAt(0).toUpperCase()}</div><div className="min-w-0"><h2 className="truncate text-lg font-bold text-slate-950">{company.name}</h2><p className="truncate text-sm text-slate-500">{company.email}</p></div></div><StatusBadge active={company.is_active} /></div><div className="mt-5 grid grid-cols-3 gap-2 text-center"><MiniMetric label="Agences" value={company.counts.agencies} /><MiniMetric label="Agents" value={company.counts.agents} /><MiniMetric label="Voyages" value={company.counts.voyages} /></div><div className="mt-5 grid gap-2 rounded-2xl bg-slate-50 p-4 text-sm sm:grid-cols-2"><div><p className="text-xs text-slate-400">Commission</p><p className="mt-1 font-bold text-slate-900">{company.commission_rate}%</p></div><div><p className="text-xs text-slate-400">À reverser</p><p className="mt-1 font-bold text-slate-900">{money(company.wallet.pending)}</p></div><div><p className="text-xs text-slate-400">Administrateur</p><p className="mt-1 truncate font-medium text-slate-700">{company.admins[0]?.email || 'Non créé'}</p></div><div><p className="text-xs text-slate-400">Création</p><p className="mt-1 font-medium text-slate-700">{shortDate(company.created_at)}</p></div></div><div className="mt-5 flex flex-wrap justify-between gap-2"><button type="button" onClick={() => void toggle(company)} className={`inline-flex items-center gap-2 rounded-xl px-3 py-2 text-sm font-semibold ${company.is_active ? 'bg-red-50 text-red-700 hover:bg-red-100' : 'bg-emerald-50 text-emerald-700 hover:bg-emerald-100'}`}><Power className="h-4 w-4" />{company.is_active ? 'Suspendre' : 'Réactiver'}</button><Link to={`/admin/compagnies/${company.id}`} className="inline-flex items-center rounded-xl bg-slate-900 px-4 py-2 text-sm font-semibold text-white hover:bg-slate-800">Ouvrir la fiche</Link></div></article>)}</section>}

    <AdminModal open={modal} onClose={() => setModal(false)} title="Créer une compagnie" description="Le compte administrateur compagnie sera créé dans la même opération." size="lg"><form onSubmit={create} className="space-y-5"><AdminError message={error} /><div className="grid gap-4 sm:grid-cols-2"><Field label="Nom de la compagnie"><input required value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })} className={inputClass} /></Field><Field label="Email professionnel"><input required type="email" value={form.email} onChange={(event) => setForm({ ...form, email: event.target.value })} className={inputClass} /></Field><Field label="Téléphone"><input required value={form.phone} onChange={(event) => setForm({ ...form, phone: event.target.value })} className={inputClass} /></Field><Field label="Commission EVEX (%)"><input required type="number" min="0" max="100" step="0.01" value={form.commission_rate} onChange={(event) => setForm({ ...form, commission_rate: event.target.value })} className={inputClass} /></Field></div><Field label="Adresse"><input required value={form.address} onChange={(event) => setForm({ ...form, address: event.target.value })} className={inputClass} /></Field><Field label="Description"><textarea rows={3} value={form.description} onChange={(event) => setForm({ ...form, description: event.target.value })} className={`${inputClass} h-auto py-3`} /></Field><div className="border-t border-slate-100 pt-5"><h3 className="font-bold text-slate-900">Compte administrateur compagnie</h3><div className="mt-4 grid gap-4 sm:grid-cols-2"><Field label="Prénom"><input value={form.admin_first_name} onChange={(event) => setForm({ ...form, admin_first_name: event.target.value })} className={inputClass} /></Field><Field label="Nom"><input value={form.admin_last_name} onChange={(event) => setForm({ ...form, admin_last_name: event.target.value })} className={inputClass} /></Field><Field label="Email de connexion"><input required type="email" value={form.admin_email} onChange={(event) => setForm({ ...form, admin_email: event.target.value })} className={inputClass} /></Field><Field label="Mot de passe initial" hint="8 caractères minimum ; un mot de passe courant sera refusé."><input required type="password" minLength={8} value={form.admin_password} onChange={(event) => setForm({ ...form, admin_password: event.target.value })} className={inputClass} /></Field></div></div><div className="flex justify-end gap-2"><SecondaryButton type="button" onClick={() => setModal(false)}>Annuler</SecondaryButton><PrimaryButton type="submit" disabled={saving}>{saving && <Loader2 className="h-4 w-4 animate-spin" />}Créer la compagnie</PrimaryButton></div></form></AdminModal>
  </AdminPageShell>;
};

export const AdminCompanyDetailPage: React.FC = () => {
  const { id } = useParams<{ id: string }>();
  const companyId = Number(id);
  const [company, setCompany] = useState<PlatformAdminCompany | null>(null);
  const [adminModal, setAdminModal] = useState(false);
  const [adminForm, setAdminForm] = useState({ first_name: '', last_name: '', email: '', password: '' });
  const [commission, setCommission] = useState('');
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const load = useCallback(async () => { setLoading(true); try { const result = await apiService.getPlatformAdminCompany(companyId); setCompany(result); setCommission(String(result.commission_rate)); setError(null); } catch (err: any) { setError(err?.message || 'Impossible de charger cette compagnie.'); } finally { setLoading(false); } }, [companyId]);
  useEffect(() => { void load(); }, [load]);
  const saveCommission = async () => { setSaving(true); try { await apiService.updatePlatformAdminCompany(companyId, { commission_rate: Number(commission) } as Partial<PlatformAdminCompany>); await load(); } catch (err: any) { setError(err?.message || 'Commission invalide.'); } finally { setSaving(false); } };
  const createAdmin = async (event: React.FormEvent) => { event.preventDefault(); setSaving(true); try { await apiService.createPlatformCompanyAdmin(companyId, adminForm); setAdminModal(false); setAdminForm({ first_name: '', last_name: '', email: '', password: '' }); await load(); } catch (err: any) { setError(err?.message || 'Création du compte impossible.'); } finally { setSaving(false); } };
  const toggle = async () => { if (!company) return; const next = !company.is_active; const reason = next ? 'Réactivation depuis la fiche compagnie' : window.prompt('Justification de la suspension :', '')?.trim(); if (!next && !reason) return; try { await apiService.setPlatformAdminCompanyStatus(company.id, next, reason || ''); await load(); } catch (err: any) { setError(err?.message || 'Mise à jour impossible.'); } };

  return <AdminPageShell title={company?.name || 'Fiche compagnie'} description="Consultez les comptes, implantations, performances et paramètres propres à ce partenaire." actions={<Link to="/admin/compagnies" className="inline-flex items-center gap-2 text-sm font-semibold text-blue-600"><ArrowLeft className="h-4 w-4" /> Retour</Link>}>
    <AdminError message={error} onRetry={() => void load()} />{loading ? <AdminLoading /> : company && <>
      <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><AdminMetricCard label="Agences" value={number(company.counts.agencies)} icon={<Store className="h-5 w-5" />} tone="blue" /><AdminMetricCard label="Administrateurs" value={number(company.admins.length)} icon={<ShieldCheck className="h-5 w-5" />} tone="violet" /><AdminMetricCard label="Agents guichet" value={number(company.counts.agents)} icon={<Users className="h-5 w-5" />} tone="emerald" /><AdminMetricCard label="À reverser" value={money(company.wallet.pending)} icon={<Building2 className="h-5 w-5" />} tone="amber" /></section>
      <section className="grid gap-6 xl:grid-cols-[1fr_0.8fr]"><article className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex items-start justify-between gap-4"><div><h2 className="text-lg font-bold text-slate-950">Informations du partenaire</h2><p className="mt-1 text-sm text-slate-500">Créée le {shortDate(company.created_at)}</p></div><StatusBadge active={company.is_active} /></div><dl className="mt-6 grid gap-5 sm:grid-cols-2"><Info label="Email" value={company.email} /><Info label="Téléphone" value={company.phone} /><Info label="Adresse" value={company.address} /><Info label="Site web" value={company.website || 'Non renseigné'} /></dl><div className="mt-6 flex gap-2"><button type="button" onClick={() => void toggle()} className={`rounded-xl px-4 py-2.5 text-sm font-semibold ${company.is_active ? 'bg-red-50 text-red-700' : 'bg-emerald-50 text-emerald-700'}`}>{company.is_active ? 'Suspendre la compagnie' : 'Réactiver la compagnie'}</button></div></article><article className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><h2 className="text-lg font-bold text-slate-950">Paramètres financiers</h2><Field label="Commission EVEX (%)"><input type="number" min="0" max="100" step="0.01" value={commission} onChange={(event) => setCommission(event.target.value)} className={inputClass} /></Field><PrimaryButton className="mt-4 w-full" onClick={() => void saveCommission()} disabled={saving}>{saving && <Loader2 className="h-4 w-4 animate-spin" />}Enregistrer la commission</PrimaryButton><div className="mt-5 rounded-2xl bg-slate-50 p-4"><p className="text-xs text-slate-500">Total déjà reversé</p><p className="mt-1 text-xl font-bold text-slate-900">{money(company.wallet.paid)}</p></div></article></section>
      <section className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex items-center justify-between gap-4"><div><h2 className="text-lg font-bold text-slate-950">Comptes administrateurs</h2><p className="mt-1 text-sm text-slate-500">Accès au portail propre à la compagnie.</p></div><PrimaryButton onClick={() => setAdminModal(true)}><Plus className="h-4 w-4" /> Ajouter</PrimaryButton></div><div className="mt-5 grid gap-3 md:grid-cols-2">{company.admins.map((admin) => <div key={admin.id} className="flex items-center justify-between rounded-2xl border border-slate-200 p-4"><div><p className="font-semibold text-slate-900">{[admin.first_name, admin.last_name].filter(Boolean).join(' ') || 'Administrateur'}</p><p className="mt-1 text-sm text-slate-500">{admin.email}</p></div><StatusBadge active={admin.is_active} /></div>)}{company.admins.length === 0 && <p className="col-span-2 py-8 text-center text-sm text-slate-500">Aucun administrateur.</p>}</div></section>
      <section className="grid gap-6 xl:grid-cols-2"><article className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><h2 className="text-lg font-bold text-slate-950">Agences</h2><div className="mt-5 space-y-3">{company.agencies?.map((agency) => <div key={agency.id} className="flex items-center justify-between rounded-2xl bg-slate-50 p-4"><div><p className="font-semibold text-slate-900">{agency.name}</p><p className="mt-1 text-xs text-slate-500">{agency.city} · {agency.counters} guichet(s)</p></div><StatusBadge active={agency.active} /></div>)}{!company.agencies?.length && <p className="py-8 text-center text-sm text-slate-500">Aucune agence.</p>}</div></article><article className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><h2 className="text-lg font-bold text-slate-950">Voyages récents</h2><div className="mt-5 space-y-3">{company.recent_trips?.map((trip) => <div key={trip.id} className="rounded-2xl bg-slate-50 p-4"><div className="flex items-center justify-between"><p className="font-semibold text-slate-900">{trip.route}</p><StatusBadge active={trip.is_active} /></div><p className="mt-1 text-xs text-slate-500">{shortDate(trip.date)} · {trip.occupancy_rate}% rempli</p></div>)}{!company.recent_trips?.length && <p className="py-8 text-center text-sm text-slate-500">Aucun voyage.</p>}</div></article></section>
    </>}
    <AdminModal open={adminModal} onClose={() => setAdminModal(false)} title="Ajouter un administrateur compagnie"><form onSubmit={createAdmin} className="space-y-4"><AdminError message={error} /><div className="grid gap-4 sm:grid-cols-2"><Field label="Prénom"><input value={adminForm.first_name} onChange={(event) => setAdminForm({ ...adminForm, first_name: event.target.value })} className={inputClass} /></Field><Field label="Nom"><input value={adminForm.last_name} onChange={(event) => setAdminForm({ ...adminForm, last_name: event.target.value })} className={inputClass} /></Field></div><Field label="Email"><input required type="email" value={adminForm.email} onChange={(event) => setAdminForm({ ...adminForm, email: event.target.value })} className={inputClass} /></Field><Field label="Mot de passe initial"><input required type="password" minLength={8} value={adminForm.password} onChange={(event) => setAdminForm({ ...adminForm, password: event.target.value })} className={inputClass} /></Field><div className="flex justify-end gap-2"><SecondaryButton type="button" onClick={() => setAdminModal(false)}>Annuler</SecondaryButton><PrimaryButton type="submit" disabled={saving}>{saving && <Loader2 className="h-4 w-4 animate-spin" />}Créer le compte</PrimaryButton></div></form></AdminModal>
  </AdminPageShell>;
};

const MiniMetric: React.FC<{ label: string; value: number }> = ({ label, value }) => <div className="rounded-xl bg-slate-50 px-3 py-3"><p className="text-lg font-extrabold text-slate-900">{number(value)}</p><p className="text-[11px] text-slate-500">{label}</p></div>;
const Info: React.FC<{ label: string; value: string }> = ({ label, value }) => <div><dt className="text-xs uppercase tracking-wide text-slate-400">{label}</dt><dd className="mt-1 text-sm font-semibold text-slate-800">{value}</dd></div>;
