import React, { useCallback, useEffect, useState } from 'react';
import { Download, KeyRound, Loader2, LogOut, Plus, Power, Search, ShieldCheck, UserRoundCheck, Users } from 'lucide-react';
import apiService from '../../services/api';
import type { PlatformAdminCompany, PlatformAdminUser } from '../../services/api';
import { AdminError, AdminLoading, AdminModal, AdminPageShell, EmptyState, Field, PrimaryButton, SecondaryButton, StatusBadge, dateTime, inputClass, selectClass } from './AdminUI';

const roleLabels: Record<string, string> = { SUPER_ADMIN: 'Admin plateforme', ADMIN_COMPAGNIE: 'Admin compagnie', AGENT_GUICHET: 'Agent guichet', CLIENT: 'Voyageur' };

const AdminUsersPage: React.FC = () => {
  const [users, setUsers] = useState<PlatformAdminUser[]>([]);
  const [companies, setCompanies] = useState<PlatformAdminCompany[]>([]);
  const [filters, setFilters] = useState({ q: '', role: '', status: '', company: '' });
  const [modal, setModal] = useState(false);
  const [form, setForm] = useState({ first_name: '', last_name: '', email: '', password: '' });
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const load = useCallback(async () => { setLoading(true); try { const [userData, companyData] = await Promise.all([apiService.getPlatformAdminUsers(filters), apiService.getPlatformAdminCompanies()]); setUsers(userData); setCompanies(companyData); setError(null); } catch (err: any) { setError(err?.message || 'Impossible de charger les utilisateurs.'); } finally { setLoading(false); } }, [filters]);
  useEffect(() => { const id = window.setTimeout(() => void load(), 250); return () => window.clearTimeout(id); }, [load]);
  const create = async (event: React.FormEvent) => { event.preventDefault(); setSaving(true); try { await apiService.createPlatformAdminUser(form); setModal(false); setForm({ first_name: '', last_name: '', email: '', password: '' }); await load(); } catch (err: any) { setError(err?.message || 'Création impossible.'); } finally { setSaving(false); } };
  const toggle = async (user: PlatformAdminUser) => { const next = !user.is_active; const reason = next ? 'Réactivation administrative' : window.prompt(`Pourquoi suspendre ${user.email} ?`, '')?.trim(); if (!next && !reason) return; try { await apiService.setPlatformAdminUserStatus(user.id, next, reason || ''); await load(); } catch (err: any) { setError(err?.message || 'Mise à jour impossible.'); } };
  const resetPassword = async (user: PlatformAdminUser) => { const password = window.prompt(`Nouveau mot de passe pour ${user.email} :`, '') || ''; if (!password) return; try { const result = await apiService.resetPlatformAdminUserPassword(user.id, password); window.alert(result.detail); } catch (err: any) { setError(err?.message || 'Réinitialisation impossible.'); } };
  const revoke = async (user: PlatformAdminUser) => { if (!window.confirm(`Déconnecter ${user.email} de toutes ses sessions ?`)) return; try { const result = await apiService.revokePlatformAdminUserSessions(user.id); window.alert(result.detail); } catch (err: any) { setError(err?.message || 'Révocation impossible.'); } };

  return <AdminPageShell title="Utilisateurs" description="Retrouvez tous les comptes de la plateforme, contrôlez leurs accès et intervenez sur les sessions en toute traçabilité." actions={<div className="flex flex-wrap gap-2"><SecondaryButton onClick={() => void apiService.downloadPlatformAdminExport('users')}><Download className="h-4 w-4" /> Exporter</SecondaryButton><PrimaryButton onClick={() => setModal(true)}><Plus className="h-4 w-4" /> Admin plateforme</PrimaryButton></div>}>
    <AdminError message={error} onRetry={() => void load()} />
    <section className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-4"><div className="relative"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-400" /><input value={filters.q} onChange={(event) => setFilters({ ...filters, q: event.target.value })} placeholder="Nom, email, téléphone" className={`${inputClass} pl-10`} /></div><select value={filters.role} onChange={(event) => setFilters({ ...filters, role: event.target.value })} className={selectClass}><option value="">Tous les rôles</option>{Object.entries(roleLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select><select value={filters.company} onChange={(event) => setFilters({ ...filters, company: event.target.value })} className={selectClass}><option value="">Toutes les compagnies</option>{companies.map((company) => <option key={company.id} value={company.id}>{company.name}</option>)}</select><select value={filters.status} onChange={(event) => setFilters({ ...filters, status: event.target.value })} className={selectClass}><option value="">Tous les statuts</option><option value="active">Actifs</option><option value="inactive">Suspendus</option></select></div></section>
    {loading ? <AdminLoading /> : users.length === 0 ? <EmptyState title="Aucun utilisateur trouvé" /> : <section className="overflow-x-auto rounded-3xl border border-slate-200 bg-white shadow-sm"><table className="min-w-full text-sm"><thead className="bg-slate-50 text-left text-xs uppercase tracking-wide text-slate-500"><tr><th className="px-5 py-3">Utilisateur</th><th className="px-5 py-3">Rôle</th><th className="px-5 py-3">Compagnie</th><th className="px-5 py-3">Dernière connexion</th><th className="px-5 py-3">Statut</th><th className="px-5 py-3 text-right">Actions</th></tr></thead><tbody className="divide-y divide-slate-100">{users.map((user) => <tr key={user.id} className="hover:bg-slate-50/70"><td className="px-5 py-4"><div className="flex items-center gap-3"><div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-blue-50 font-bold text-blue-700">{(user.first_name || user.email).charAt(0).toUpperCase()}</div><div><p className="font-semibold text-slate-900">{[user.first_name, user.last_name].filter(Boolean).join(' ') || 'Sans nom'}</p><p className="text-xs text-slate-500">{user.email}{user.phone ? ` · ${user.phone}` : ''}</p></div></div></td><td className="px-5 py-4"><span className="inline-flex items-center gap-1.5 rounded-full bg-violet-50 px-2.5 py-1 text-xs font-semibold text-violet-700">{user.role === 'SUPER_ADMIN' && <ShieldCheck className="h-3.5 w-3.5" />}{roleLabels[user.role]}</span></td><td className="px-5 py-4 text-slate-600">{user.company_name || '—'}</td><td className="whitespace-nowrap px-5 py-4 text-slate-500">{dateTime(user.last_login)}</td><td className="px-5 py-4"><StatusBadge active={user.is_active} /></td><td className="px-5 py-4"><div className="flex justify-end gap-1"><button type="button" onClick={() => void resetPassword(user)} title="Réinitialiser le mot de passe" className="rounded-lg p-2 text-slate-500 hover:bg-blue-50 hover:text-blue-700"><KeyRound className="h-4 w-4" /></button><button type="button" onClick={() => void revoke(user)} title="Révoquer les sessions" className="rounded-lg p-2 text-slate-500 hover:bg-amber-50 hover:text-amber-700"><LogOut className="h-4 w-4" /></button><button type="button" onClick={() => void toggle(user)} title={user.is_active ? 'Suspendre' : 'Réactiver'} className={`rounded-lg p-2 ${user.is_active ? 'text-red-600 hover:bg-red-50' : 'text-emerald-600 hover:bg-emerald-50'}`}><Power className="h-4 w-4" /></button></div></td></tr>)}</tbody></table></section>}
    <AdminModal open={modal} onClose={() => setModal(false)} title="Créer un administrateur plateforme" description="Ce compte aura accès à toute l’administration générale."><form onSubmit={create} className="space-y-4"><AdminError message={error} /><div className="grid gap-4 sm:grid-cols-2"><Field label="Prénom"><input value={form.first_name} onChange={(event) => setForm({ ...form, first_name: event.target.value })} className={inputClass} /></Field><Field label="Nom"><input value={form.last_name} onChange={(event) => setForm({ ...form, last_name: event.target.value })} className={inputClass} /></Field></div><Field label="Email"><input required type="email" value={form.email} onChange={(event) => setForm({ ...form, email: event.target.value })} className={inputClass} /></Field><Field label="Mot de passe"><input required type="password" minLength={8} value={form.password} onChange={(event) => setForm({ ...form, password: event.target.value })} className={inputClass} /></Field><div className="rounded-2xl bg-amber-50 p-4 text-sm text-amber-800"><div className="flex gap-2"><UserRoundCheck className="mt-0.5 h-4 w-4 shrink-0" /><p>Réservez ce rôle aux personnes responsables de toute la plateforme.</p></div></div><div className="flex justify-end gap-2"><SecondaryButton type="button" onClick={() => setModal(false)}>Annuler</SecondaryButton><PrimaryButton type="submit" disabled={saving}>{saving ? <Loader2 className="h-4 w-4 animate-spin" /> : <Users className="h-4 w-4" />}Créer</PrimaryButton></div></form></AdminModal>
  </AdminPageShell>;
};

export default AdminUsersPage;
