# Generated by Django 5.1.4 on 2026-07-18 20:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("transport", "0008_alter_userprofile_phone"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AgentGuichet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=150)),
                ("prenom", models.CharField(max_length=150)),
                ("telephone", models.CharField(max_length=30)),
                ("actif", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "compagnie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agents_guichet",
                        to="transport.company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="agents_crees",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agentguichet",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VenteGuichet",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("client_nom", models.CharField(max_length=200)),
                ("client_telephone", models.CharField(max_length=30)),
                ("montant_billet", models.IntegerField()),
                ("frais_evex", models.IntegerField(default=300)),
                ("montant_total", models.IntegerField()),
                (
                    "mode_paiement",
                    models.CharField(
                        choices=[
                            ("cash", "Cash"),
                            ("flooz", "Flooz"),
                            ("tmoney", "T-Money"),
                        ],
                        max_length=10,
                    ),
                ),
                ("reference_vente", models.CharField(max_length=64, unique=True)),
                ("qr_code_data", models.TextField()),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("valide", "Valide"),
                            ("annule", "Annule"),
                            ("utilise", "Utilise"),
                        ],
                        default="valide",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ventes",
                        to="guichet.agentguichet",
                    ),
                ),
                (
                    "siege",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ventes_guichet",
                        to="transport.siege",
                    ),
                ),
                (
                    "voyage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ventes_guichet",
                        to="transport.scheduledtrip",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ControlePassager",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "resultat",
                    models.CharField(
                        choices=[
                            ("valide", "Valide"),
                            ("invalide", "Invalide"),
                            ("deja_utilise", "Deja utilise"),
                        ],
                        max_length=20,
                    ),
                ),
                ("message", models.CharField(blank=True, max_length=400)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "agent",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="controles",
                        to="guichet.agentguichet",
                    ),
                ),
                (
                    "reservation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="controles",
                        to="transport.reservation",
                    ),
                ),
                (
                    "voyage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="controles",
                        to="transport.scheduledtrip",
                    ),
                ),
                (
                    "vente",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="controles",
                        to="guichet.venteguichet",
                    ),
                ),
            ],
        ),
    ]
