# Generated by Django 5.1.4 on 2025-12-05 10:38

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom de la ville')),
                ('region', models.CharField(max_length=100, verbose_name='Région')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ville active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
            ],
            options={
                'verbose_name': 'Ville',
                'verbose_name_plural': 'Villes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passenger_name', models.CharField(max_length=200, verbose_name='Nom du passager')),
                ('passenger_email', models.EmailField(max_length=254, verbose_name='Email du passager')),
                ('passenger_phone', models.CharField(max_length=20, verbose_name='Téléphone du passager')),
                ('seat_number', models.CharField(max_length=10, verbose_name='Numéro de siège')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('confirmed', 'Confirmé'), ('cancelled', 'Annulé'), ('completed', 'Terminé')], default='pending', max_length=20, verbose_name='Statut')),
                ('payment_method', models.CharField(choices=[('mobile_money', 'Mobile Money'), ('bank_card', 'Carte bancaire'), ('cash', 'Espèces')], max_length=20, verbose_name='Méthode de paiement')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix total (FCFA)')),
                ('booking_date', models.DateTimeField(auto_now_add=True, verbose_name='Date de réservation')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Réservation',
                'verbose_name_plural': 'Réservations',
                'ordering': ['-booking_date'],
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom de la compagnie')),
                ('description', models.TextField(verbose_name='Description')),
                ('address', models.CharField(max_length=300, verbose_name='Adresse')),
                ('phone', models.CharField(max_length=20, verbose_name='Téléphone')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Site web')),
                ('logo', models.URLField(blank=True, null=True, verbose_name='URL du logo')),
                ('is_active', models.BooleanField(default=True, verbose_name='Compagnie active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour')),
                ('admin_user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_admin', to=settings.AUTH_USER_MODEL, verbose_name='Administrateur de la compagnie')),
                ('admins', models.ManyToManyField(blank=True, related_name='admin_companies', to=settings.AUTH_USER_MODEL, verbose_name='Administrateurs')),
            ],
            options={
                'verbose_name': 'Compagnie',
                'verbose_name_plural': 'Compagnies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('booking_confirmation', 'Confirmation de réservation'), ('booking_reminder', 'Rappel de réservation'), ('payment_confirmation', 'Confirmation de paiement'), ('trip_update', 'Mise à jour du trajet'), ('system', 'Notification système')], default='system', max_length=50, verbose_name='Type')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('message', models.TextField(verbose_name='Message')),
                ('is_read', models.BooleanField(default=False, verbose_name='Lu')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant (FCFA)')),
                ('payment_method', models.CharField(choices=[('mobile_money', 'Mobile Money'), ('bank_card', 'Carte bancaire'), ('cash', 'Espèces')], max_length=20, verbose_name='Méthode de paiement')),
                ('transaction_id', models.CharField(max_length=100, unique=True, verbose_name='ID de transaction')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('completed', 'Complété'), ('failed', 'Échoué'), ('refunded', 'Remboursé')], default='pending', max_length=20, verbose_name='Statut')),
                ('evex_commission', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Commission Evex (FCFA)')),
                ('company_revenue', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Revenu Compagnie (FCFA)')),
                ('payment_date', models.DateTimeField(auto_now_add=True, verbose_name='Date de paiement')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='transport.booking', verbose_name='Réservation')),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
                'ordering': ['-payment_date'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1 étoile'), (2, '2 étoiles'), (3, '3 étoiles'), (4, '4 étoiles'), (5, '5 étoiles')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Note')),
                ('comment', models.TextField(verbose_name='Commentaire')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='transport.booking', verbose_name='Réservation')),
            ],
            options={
                'verbose_name': 'Avis',
                'verbose_name_plural': 'Avis',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_time', models.TimeField(verbose_name='Heure de départ')),
                ('arrival_time', models.TimeField(verbose_name="Heure d'arrivée")),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Prix (FCFA)')),
                ('duration', models.PositiveIntegerField(help_text='Durée en minutes', verbose_name='Durée (minutes)')),
                ('bus_type', models.CharField(choices=[('Standard', 'Standard'), ('Premium', 'Premium'), ('VIP', 'VIP'), ('Luxury', 'Luxury')], default='Standard', max_length=20, verbose_name='Type de bus')),
                ('capacity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Capacité (places)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Trajet actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour')),
                ('arrival_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrival_trips', to='transport.city', verbose_name="Ville d'arrivée")),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='transport.company', verbose_name='Compagnie')),
                ('departure_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departure_trips', to='transport.city', verbose_name='Ville de départ')),
            ],
            options={
                'verbose_name': 'Trajet',
                'verbose_name_plural': 'Trajets',
                'ordering': ['departure_time'],
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='transport.trip', verbose_name='Trajet'),
        ),
        migrations.CreateModel(
            name='TripStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField(verbose_name='Ordre')),
                ('segment_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name="Prix du segment vers l'arrêt suivant")),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transport.city', verbose_name='Ville')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='transport.trip')),
            ],
            options={
                'verbose_name': 'Arrêt',
                'verbose_name_plural': 'Arrêts',
                'ordering': ['trip', 'sequence'],
                'unique_together': {('trip', 'sequence')},
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='destination_stop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='destination_bookings', to='transport.tripstop'),
        ),
        migrations.AddField(
            model_name='booking',
            name='origin_stop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='origin_bookings', to='transport.tripstop'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, help_text='Format: +228 XX XX XX XX', max_length=20, null=True, verbose_name='Numéro de téléphone')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil utilisateur',
                'verbose_name_plural': 'Profils utilisateurs',
            },
        ),
        migrations.CreateModel(
            name='ScheduledTrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('available_seats', models.PositiveIntegerField(default=0, verbose_name='Places disponibles')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_trips', to='transport.trip')),
            ],
            options={
                'verbose_name': 'Voyage programmé',
                'verbose_name_plural': 'Voyages programmés',
                'ordering': ['-date'],
                'unique_together': {('trip', 'date')},
            },
        ),
        migrations.CreateModel(
            name='BoardingZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom de la zone')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boarding_zones', to='transport.city', verbose_name='Ville')),
                ('trip_stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boarding_zones', to='transport.tripstop', verbose_name='Arrêt de trajet')),
            ],
            options={
                'verbose_name': "Zone d'embarquement",
                'verbose_name_plural': "Zones d'embarquement",
                'unique_together': {('trip_stop', 'name')},
            },
        ),
    ]
