# Generated by Django 5.1.4 on 2026-06-15 11:57

import transport.models.base
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transport", "0001_add_pin_and_nullable_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="expires_at",
            field=models.DateTimeField(
                default=transport.models.base.get_reservation_expiry
            ),
        ),
    ]
