# Generated by Django 5.1.4 on 2026-01-08 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='scheduled_trip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='transport.scheduledtrip', verbose_name='Voyage programmé'),
        ),
    ]
