# Generated by Django 5.2.6 on 2025-09-24 15:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transport", "0002_alter_company_admin_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="admins",
            field=models.ManyToManyField(
                blank=True,
                related_name="admin_companies",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Administrateurs",
            ),
        ),
    ]
