# Generated by Django 5.1.4 on 2025-10-08 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0003_company_admins'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledTrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date du voyage')),
                ('is_active', models.BooleanField(default=True, verbose_name='Voyage actif')),
                ('available_seats', models.PositiveIntegerField(blank=True, null=True, verbose_name='Places disponibles')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_trips', to='transport.trip', verbose_name='Trajet')),
            ],
            options={
                'verbose_name': 'Voyage planifié',
                'verbose_name_plural': 'Voyages planifiés',
                'ordering': ['date', 'trip__departure_time'],
                'unique_together': {('trip', 'date')},
            },
        ),
    ]
