# Generated by Django 5.1.4 on 2025-10-18 22:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0004_scheduledtrip'),
    ]

    operations = [
        migrations.CreateModel(
            name='TripStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField(verbose_name='Ordre')),
                ('segment_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name="Prix du segment vers l'arrêt suivant")),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transport.city', verbose_name='Ville')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='transport.trip')),
            ],
            options={
                'ordering': ['trip', 'sequence'],
                'unique_together': {('trip', 'sequence')},
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='destination_stop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='destination_bookings', to='transport.tripstop'),
        ),
        migrations.AddField(
            model_name='booking',
            name='origin_stop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='origin_bookings', to='transport.tripstop'),
        ),
    ]
