# Generated by Django 5.1.4 on 2026-05-31 09:02

import django.db.models.deletion
import uuid
from django.db import migrations, models
from django.utils import timezone
from datetime import timedelta


def get_expires_at():
    """Calcul de la date d'expiration de la réservation (5 minutes)"""
    return timezone.now() + timedelta(minutes=5)


class Migration(migrations.Migration):

    dependencies = [
        ("transport", "0004_booking_created_by_booking_deleted_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompteCagnotte",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("solde_a_reverser", models.IntegerField(default=0)),
                ("total_reverse", models.IntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "compagnie",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cagnotte",
                        to="transport.company",
                        verbose_name="Compagnie",
                    ),
                ),
            ],
            options={
                "verbose_name": "Compte cagnotte",
                "verbose_name_plural": "Comptes cagnotte",
            },
        ),
        migrations.CreateModel(
            name="Reservation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "client_nom",
                    models.CharField(max_length=200, verbose_name="Nom du client"),
                ),
                (
                    "client_telephone",
                    models.CharField(max_length=30, verbose_name="Telephone du client"),
                ),
                ("montant_billet", models.IntegerField(verbose_name="Montant billet")),
                (
                    "frais_evex",
                    models.IntegerField(default=300, verbose_name="Frais EVEX"),
                ),
                ("montant_total", models.IntegerField(verbose_name="Montant total")),
                ("frais_qos", models.IntegerField(verbose_name="Frais QOS")),
                (
                    "revenu_net_evex",
                    models.IntegerField(verbose_name="Revenu net EVEX"),
                ),
                (
                    "montant_reverse_compagnie",
                    models.IntegerField(verbose_name="Montant reverse compagnie"),
                ),
                (
                    "operateur",
                    models.CharField(
                        choices=[("FLOOZ", "Flooz"), ("TMONEY", "T-Money")],
                        max_length=10,
                    ),
                ),
                ("reference_evex", models.CharField(max_length=32, unique=True)),
                (
                    "reference_qos",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "transaction_id_qos",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "statut_paiement",
                    models.CharField(
                        choices=[
                            ("en_attente", "En attente"),
                            ("paye", "Paye"),
                            ("echoue", "Echoue"),
                            ("expire", "Expire"),
                            ("rembourse", "Rembourse"),
                        ],
                        default="en_attente",
                        max_length=20,
                    ),
                ),
                ("reversement_effectue", models.BooleanField(default=False)),
                ("reversement_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                (
                    "expires_at",
                    models.DateTimeField(
                        default=get_expires_at
                    ),
                ),
                (
                    "voyage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reservations_evex",
                        to="transport.scheduledtrip",
                        verbose_name="Voyage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Reservation EVEX",
                "verbose_name_plural": "Reservations EVEX",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="HistoriqueReversement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("montant", models.IntegerField()),
                (
                    "reference_qos_reversement",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("en_attente", "En attente"),
                            ("effectue", "Effectue"),
                            ("echoue", "Echoue"),
                        ],
                        default="en_attente",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "compagnie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historiques_reversement",
                        to="transport.company",
                    ),
                ),
                (
                    "reservation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historiques_reversement",
                        to="transport.reservation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Historique reversement",
                "verbose_name_plural": "Historiques reversement",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Siege",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("numero", models.IntegerField(verbose_name="Numero de siege")),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("libre", "Libre"),
                            ("reserve_temp", "Reserve temporairement"),
                            ("occupe", "Occupe"),
                        ],
                        default="libre",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "reserve_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Reserve le"
                    ),
                ),
                (
                    "voyage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sieges",
                        to="transport.scheduledtrip",
                        verbose_name="Voyage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Siege",
                "verbose_name_plural": "Sieges",
                "ordering": ["voyage", "numero"],
                "unique_together": {("voyage", "numero")},
            },
        ),
        migrations.AddField(
            model_name="reservation",
            name="siege",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="reservations",
                to="transport.siege",
                verbose_name="Siege",
            ),
        ),
    ]
