# Generated by Django 5.1.4 on 2025-11-13 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0006_remove_booking_notes_remove_booking_travel_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardingZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom de la zone')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boarding_zones', to='transport.city', verbose_name='Ville')),
                ('trip_stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boarding_zones', to='transport.tripstop', verbose_name='Arrêt de trajet')),
            ],
            options={
                'verbose_name': "Zone d'embarquement",
                'verbose_name_plural': "Zones d'embarquement",
                'unique_together': {('trip_stop', 'name')},
            },
        ),
    ]
