# Generated by Django 5.1.4 on 2026-06-15 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("transport", "0002_alter_reservation_expires_at"),
        ("transport", "0006_phone_unique"),
    ]

    operations = []
