# Generated by Django 5.1.4 on 2025-11-13 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0007_boardingzone'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='company_revenue',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Revenu Compagnie (FCFA)'),
        ),
        migrations.AddField(
            model_name='payment',
            name='evex_commission',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Commission Evex (FCFA)'),
        ),
    ]
