# Generated by Django 5.1.4 on 2026-07-18 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transport", "0007_merge_20260615_1221"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="phone",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Format canonique: 228XXXXXXXX (ex: 22890123456)",
                max_length=20,
                null=True,
                unique=True,
                verbose_name="Numéro de téléphone",
            ),
        ),
    ]
