# Generated by Django 5.1.4 on 2026-08-04 22:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_completed_trip_xp(apps, schema_editor):
    Booking = apps.get_model('transport', 'Booking')
    UserProfile = apps.get_model('transport', 'UserProfile')
    XPTransaction = apps.get_model('transport', 'XPTransaction')

    completed_bookings = Booking.objects.filter(
        status='completed',
        user_id__isnull=False,
    ).iterator()
    for booking in completed_bookings:
        _, created = XPTransaction.objects.get_or_create(
            event_key=f'booking:{booking.pk}:completed',
            defaults={
                'user_id': booking.user_id,
                'booking_id': booking.pk,
                'event_type': 'trip_completed',
                'points': 100,
                'description': 'Voyage EVEX terminé',
            },
        )
        if created:
            profile, _ = UserProfile.objects.get_or_create(user_id=booking.user_id)
            profile.xp_total += 100
            profile.save(update_fields=['xp_total'])


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0009_platformconfiguration_company_commission_rate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='xp_total',
            field=models.PositiveIntegerField(default=0, verbose_name='XP cumulés'),
        ),
        migrations.CreateModel(
            name='XPTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_key', models.CharField(max_length=100, unique=True)),
                ('event_type', models.CharField(choices=[('trip_completed', 'Voyage terminé'), ('trip_reversed', 'Voyage annulé ou remboursé'), ('adjustment', 'Ajustement administratif')], max_length=30)),
                ('points', models.IntegerField()),
                ('description', models.CharField(max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='xp_transactions', to='transport.booking')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xp_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transaction XP',
                'verbose_name_plural': 'Transactions XP',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='transport_x_user_id_f07632_idx')],
            },
        ),
        migrations.RunPython(backfill_completed_trip_xp, migrations.RunPython.noop),
    ]
