# Generated by Django 5.1.4 on 2026-08-04 23:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0010_userprofile_xp_total_xptransaction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TripTrackingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('accuracy_m', models.FloatField(blank=True, null=True)),
                ('speed_kmh', models.FloatField(blank=True, null=True)),
                ('heading', models.FloatField(blank=True, null=True)),
                ('delay_minutes', models.IntegerField(default=0)),
                ('passed_stop_ids', models.JSONField(blank=True, default=list)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('stopped_at', models.DateTimeField(blank=True, null=True)),
                ('last_position_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driven_tracking_sessions', to=settings.AUTH_USER_MODEL)),
                ('scheduled_trip', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_session', to='transport.scheduledtrip')),
            ],
            options={
                'verbose_name': 'Suivi GPS de voyage',
                'verbose_name_plural': 'Suivis GPS de voyage',
            },
        ),
        migrations.CreateModel(
            name='BusPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('accuracy_m', models.FloatField(blank=True, null=True)),
                ('speed_kmh', models.FloatField(blank=True, null=True)),
                ('heading', models.FloatField(blank=True, null=True)),
                ('recorded_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='transport.triptrackingsession')),
            ],
            options={
                'verbose_name': 'Position du bus',
                'verbose_name_plural': 'Positions du bus',
                'ordering': ['-recorded_at', '-id'],
                'indexes': [models.Index(fields=['session', '-recorded_at'], name='transport_b_session_c20ff7_idx')],
            },
        ),
    ]
