# Generated by Django 5.1.4

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0011_triptrackingsession_busposition'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SafetyIncident',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('incident_type', models.CharField(choices=[('accident', 'Accident'), ('breakdown', 'Panne'), ('medical', 'Urgence médicale'), ('road_hazard', 'Danger sur la route'), ('security', 'Problème de sécurité'), ('other', 'Autre incident')], max_length=24)),
                ('travel_state', models.CharField(choices=[('continuing', 'Le véhicule peut continuer'), ('stopped', 'Le véhicule est à l’arrêt'), ('unknown', 'État inconnu')], default='unknown', max_length=16)),
                ('severity', models.CharField(choices=[('low', 'Faible'), ('medium', 'Modérée'), ('high', 'Élevée'), ('critical', 'Critique')], max_length=12)),
                ('status', models.CharField(choices=[('reported', 'Signalé'), ('acknowledged', 'Pris en charge'), ('resolved', 'Résolu')], default='reported', max_length=16)),
                ('description', models.TextField(blank=True, max_length=1000)),
                ('public_message', models.CharField(max_length=300)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('accuracy_m', models.FloatField(blank=True, null=True)),
                ('location_recorded_at', models.DateTimeField(blank=True, null=True)),
                ('location_source', models.CharField(choices=[('device', 'Appareil du déclarant'), ('tracking', 'Dernière position du suivi'), ('unavailable', 'Indisponible')], default='unavailable', max_length=16)),
                ('injured_count', models.PositiveSmallIntegerField(default=0)),
                ('emergency_services_contacted', models.BooleanField(default=False)),
                ('idempotency_key', models.UUIDField(editable=False, unique=True)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_note', models.TextField(blank=True, max_length=2000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_safety_incidents', to=settings.AUTH_USER_MODEL)),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_safety_incidents', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_safety_incidents', to=settings.AUTH_USER_MODEL)),
                ('scheduled_trip', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='safety_incidents', to='transport.scheduledtrip')),
                ('tracking_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='safety_incidents', to='transport.triptrackingsession')),
            ],
            options={
                'verbose_name': 'Incident de sécurité',
                'verbose_name_plural': 'Incidents de sécurité',
                'ordering': ['-occurred_at', '-created_at'],
                'indexes': [models.Index(fields=['scheduled_trip', 'status'], name='safety_trip_status_idx'), models.Index(fields=['severity', 'status'], name='safety_severity_status_idx'), models.Index(fields=['-created_at'], name='safety_created_idx')],
                'constraints': [
                    models.CheckConstraint(condition=models.Q(('accuracy_m__isnull', True), ('latitude__isnull', True), ('location_recorded_at__isnull', True), ('location_source', 'unavailable'), ('longitude__isnull', True)) | models.Q(('latitude__gte', -90), ('latitude__isnull', False), ('latitude__lte', 90), ('location_recorded_at__isnull', False), ('location_source__in', ['device', 'tracking']), ('longitude__gte', -180), ('longitude__isnull', False), ('longitude__lte', 180)), name='safety_location_consistent'),
                    models.CheckConstraint(condition=models.Q(('accuracy_m__isnull', True)) | models.Q(('accuracy_m__gte', 0), ('accuracy_m__lte', 100000)), name='safety_accuracy_valid'),
                    models.CheckConstraint(condition=models.Q(('injured_count__lte', 999)), name='safety_injured_count_valid'),
                    models.CheckConstraint(condition=models.Q(models.Q(('status', 'resolved'), _negated=True), models.Q(('resolved_at__isnull', False), models.Q(('resolution_note', ''), _negated=True)), _connector='OR'), name='safety_resolution_consistent'),
                    models.CheckConstraint(condition=models.Q(('status', 'reported')) | models.Q(('acknowledged_at__isnull', False)), name='safety_acknowledged_consistent'),
                ],
            },
        ),
    ]
